---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:
  - name: Generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  #- name: Audit
  #  image: node:12
  #  commands:
  #    - npm audit --package-lock-only --audit-level=moderate --production

  - name: Install
    image: node:12
    commands:
      - npm ci
    environment:
      # Cannot be true because of node-sass
      NPM_CONFIG_IGNORE_SCRIPTS: false

  - name: test
    image: node:12
    commands:
      - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: Build
    image: node:12
    commands:
      - npm run build

  - name: Static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: Docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-cyrillux
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: Publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: tlVfiMhFqJ4f4g+cUxz77uwiiqSjeM9sHfHphTr/J4yyACaOcRMDVxtIFYiZ0xfNd9E=
---
kind: secret
name: docker_password
data: GpbtGdyd5kKe9jCk9g5PRTN8L9NA7eLSe6AIiiT8oJ/7QFRpQeG3ADpqGhgfDYdy72O7/lEikoEVvtD/yRmu9E6CYHy0arDab3U734oa3vHduGb7e859uai5S2s=
---
kind: secret
name: ssh_key
data: V9txLwA/bDO4nXX3y2x1o85U9vB74GtjMGrgWKuDBugj+PeNpgQzIawuPXO0cFftfIfbsvudWl25LZ3SHgMmNMhdCRBKgoABgJ1O7qT0jgCfkJVHTGpT//hSD07jKBOtrTwOY7oTOpiGQ2rHRVFGxl6nR0+PTZYArAAW5D22LWIsO2gKn4iPb7O0KQd0LeL4bIUZinyzoqVQlUOVzfuk2PZQCtn2Z5SE2jP5i0UrrsdJ9AfHcKatMRdOEE/2Gr5XQO15Z2hlWmMkUqQ9FiphBzP7vaYztN8TXJp66GZxPI/HhWWlDfvxqJ3+nbWgCdHH9YMjTn/rbfSV3v+E97vbd3sZabugl/tp1e/PU/dGXNbEwPKMpbpOItMHRa7IyNsNin9iyF4go3bQiu0KgevIVJ5K5uTJAAwhSpQgvz94oCIWITFEjxA4ld0E+heB9zxI7VpZ0tyPSnHLnoKakqw65iTKmc0KOk6Phq0XljzWowwhXCuiZsLNU2XcJqHZnEV7U43hCHGP8lc23UBHthYDxTRaagU2yH2XUkTw/FF0HbexFpCFWLflVquniNOnV1B6lAlOSSuz5cWDu2LUeRdkXfEgPOYyTjAdSGAlfC/p3YgOXE+bsNKL7Fnfh13JbCI3n39zYfxiH+0O3NHScNqgEoyGB81PaOA/uo4Ll7W5rgbkeyF0/miOZ0JTzarNlQg5EIwODkZX7nF3/lmPiWHLARKmPCuiH0a6WxsTwP9ADP4DIX7jpYcwVNhc7oxS4U9BaB5MSTTwRRzSUPfSRpInI6ogXpUOi9Rz3BMRQdO0TeU9PsRRjx0NLKtMZGZ53nQn0t48FRyKH2py26cF4Z/0LIfvfgq64LvFY+aK/B0FGm94OqMv4VRxJlv/Gm1im8PcSdbbKuO9wkjfulUJtrXaMo0jz6em2uAvCgEDdYAANjH3OkwUc8zSKOdJbJREvjlqMb/h7a9eFRmaQclz0DxS9A8ic03lJNzIy/lfcHFowZhWHb0A+euT3ADfHWwvy4gATvm4mfVyLLUbeemEuhsY1tjlYQKvSnV0AEJF+BdzwH5QTQ+ckV2YwVXIh+GOeQAgLQkKp1tjRa/1pAscerPUlRFVLHq1ftZBdWHsQPO/Q/YnXnY2RM6KYAW5aG/covueRtsr4KA3FUAjspidN2nz/sqSKoe1EtYkcHd0GpXwn+cdYcufy02aMwY3om88VovCUkLBhhPs4CM/WC9cv6TChdHUQGzBG74S7LwQbq4g5AeaHbB15VpylEUYa3ML5eE/CZ66DOPw727JtIEELrAZBl8HMdggSSbe2RlYmVUNDvsRbbhDKKPHlT2dq6KRvT8M9tv93NYE5BVyNjpclrv5Yqn2mbQIUjMLUSKQk9WwZ41pmXrS1EB/5PQwgeT+E9pBAg6nofL9Ju6mo+caGVfxVjdpp/x2tsPIEEaoihPWdZbqvaq2UK1WgwKWnPDNKWqpYJMUFsj03nw2gn69tT9+O1mMzeDExJRSDs9q4sELjJDH7bvm+ANPf3x2a8gcsYBiMhnlj1LqXlhldHThIVhH1oBJrb0pq9vr8RAHMwh8R5Gp0O0/qmuqfTPOr+30HDnCCyLRR+CcD+J7sDIfPUlORUmz/l+tPlpiP2x2dAnTHvS/cCG+nskegcF5TdqvhjC9X+yYfYbpVU5bXZjmwTiC3cgd5jX6GHf+jlaWhb9mH4WsPoIxKAn4BZlbTOxK8aY4wdoCEeGNrorrKDd8bZHUzeu3te/DbjKtJq8xMuAlOG+0YH3ZtjIa7baSF34m4jnhC/WkQevhdPmtii5Zzg1vOtxsUt7J5DFgtlMHIbmH7bVqGOpFV0TQkKt8XzthbEHweo1S8f7of46AXO7ik/jF9g9xVJ2iFvh8NMl7pQmg3GMzWUsbF0kVIFvyw2/4XgEtVE87w+LjczZ8698nCrzy9VxhzrQjsMuYPUdsbKfDGs1DPJYvazpbnyouiU8Gpo7MpBlOdM06xGir6pMuksU81DqesN7w1uOWIkBrLVgs/ywBLjemqgqxjHKhZs6xuc9TIKEUOFRqfK5NC67BQorL0zgZSyzOGS6fMpQvfwGmhV2tnuBR99cqi8X0jhNdJUbqmPw60hpFBTa1r+WyxzOjjpFuCHuxA3edXnmEddkLXVF1/13/G+/hswLgUpbebooSwDDUZa1B1+cBNYW2iuXSBZH0p/MXBuf9GHuOWwnFUCUVsqIbVJ4CEXXktmYLc2WcpWZDZpRlZhH+6RqNbO8JcBKWZdUlHw+xpEoBHXzuMsHp/BBw2EeXTFBCjhPNBRC6sQzCQ04qeRbhgxDf72i4gd84PepDCrk9BQomehXw3/lJE0yIb6QNHEBoz7/5Kqx/DIOL2CtQ0Sb/DSKMkbeIRjHlZ58JC26S3XtTyhgc/i7hwQh+1q4jjPTFVk7ZAujdqlICXIc4+WQGcGgsmDq3chVAKBtW+BPLkGWgdFfT87ocfnUZvtV/JOONOnoK7lpn8F9kzjArJdHo25VlH2hriUqifPKbX4axxRIQcZezA5XJwAt9JsznzlvhQ083Jp05gfgjim5n8EmgtyD9ps1p6t9kqNKuvec1cDs7+u8xq30//CgKeRIGctlXh9hjAy0ImlybUT8Q/3+tWSXBZGKJWlhgcHP4QQXEwgtaYnew3sgFcpeNLeOJ61hMnfPW0At+vFZraeQnAG4EBn64jsytE8yf92Fe42Dkju9oZy0R1DmsUSowe7QbnXRe2RtwxtkT3uqiLMCp9ga98VEHv9jl2vV6rXltLvsbtH66+XcALo+TZa70VSnuYpc4WgjqUKnxq9k/yY1imkdsy7Ju8M864LWTGi49+nE1xzvfzi7qrno7wNsx/1IYbCyuEPo5VfWYMtI6fK6MFOIZ7z1NMHXlS9b20NCrcRNrpR0FoyVCq7rwshMhg1ewNmwaGVKKapLIhxxnAwHFQ7e/TWo4gUeg0TnzgOio08EnFtb/suiYS0SiAidtJ5EtJAMmasU89vXWoe2ugxfmnp3jrSX7
---
kind: secret
name: gpg_key
data: /IGFYVcNiueCgH1tI9iR0vMgq2Y+HQY9PM4kLtldezqwZ7c84W6qq3c1r2rEdO/wTDPYeBZtijWkba3ui+MffIj0le1bdQKYWLZVfscBqPI0FbNtINkQ8E5Wvs6XTeJTdXpefTHy+6olYHDagFkM3jdQ/7um6/GiTZEqZ7wrLZ0uoxdJQLVxAQe4GBwHn3qcXcYhAiiBi9nr7i6xJfQZLKKgqY6zgz7jv+rOhQG154Kdzko92F4Gw5wt/L5tj9wOeHp0vB5Wxvi4Cx7U3zCSLFqjSXCJpO2MufXs3YKRG7qVMlMqP8CIp8auO5VDYAzZqh+RL3Vas5FDn7dVp0j5XqHEGOMAxBPjCXNXKbGQnak79lrnSvsmQWD17aH9IIAsP7qoEEF4l0bD4Dvm48PvGOGGFzRBX2iNyLGeuy9gsqkWFGcB87sRN2jPn928h6z7fn+mNfWu0OYD1mAQezAC1L6bYTlNaeGAe1cN2QEHsxPTY/Zv1lleg4Cv1MCx4O0FK9A9g5hrRHx+TU/QFkxJn/Q7rik1VMxIkjpL51EeqXkJfdvNONdvA/Zaai1YuWcnb4BiSxP/4K75FlHEB9wZ+NnShwmnIqnllMuOsGA3akPvu3e8FKChFpHci30um8e8VOzZzOsV233PnF2mUBr2lT0v6gBfjsIQS8YwxSVjtPc4AmSSarZgZs1L1Cg0QZci59FLRGm3xW/tGKHvkKGEXglS/gOSAdjPrkv4z5djmb6ilvCz7i6Sj8OEfC6WDyKQ7FgcAq2nAsDxYnXPx62BJ2gnTNmn1O3sLLHrDhLvvUpHDElgQLtol7ZU4jOhd0SJV0vQG10NatAHOaibd5AwMALOAhMqQTlMaOMtZg3qk4E6pO8/8+Q+U9/CI5DnH6ah91180PtcfGoBTfcKz69l//vDWK1fOeJ0WSNqtX1R9sUj8/Kq5kqdn9rSrYUjU8NxJUWhaaoybDzTBbZqYciMxqrZapHjaPKDytDCriBBJFOtEZkCcrZYdFAVgW6GEzOCVHhXpJXSckH0VMKlV1SwQpC9bTcPfwMyxKDUK+XqF8ZCM1AD+7ho0B4Vf1inbElFf2v0YdQgawuuNc8QDchxDcugeiamxdTxa+23FuhaB34GcxFSp2Za9aTC1x/V3pRlYFGq11F1oylp7G1t4teij53okBZcPvK5MOdcCWvakkbahZJJvMFpqLaHQRRf4LX+mJa1VY9RY3XLdXEkgIwGHWfW99Q+b4pVWs8yGgM7u3efCTqpWG10YAbccvN6wDHaT9xfY/z6lKjxueAfDlX+bmqlQqGT5agsYT9GgfK6fc+JePSMdNjGFD0NaSUZVbh5NXz6QrUMQfg8IzgYUKUN0wItI/5GhmJT4TEcCEAIWuxsplb9niCcRmRM3Ra6wsf/GCXgQyEmS0ZcbgdKrOpIK9DGOuH+BbvH9Z5jTY1xUGpb3pmx+W0+bnl1v9lEJtrQDmjn8IpQCsw7ufAhjPEq2I5t0aDazQ5OV79KIiOKxOWcN2EgpaBUv2n3nvXFBF6uYTjeb4/I5zYKSETOFSNueMrrDETXv14IgEBFxudru5XflctHdsNEWx58migjLg0ZeNGExNYl8d7Q5KiUUVK+xyGzBviUB67Ys8PGw9RC+S98uOPcDi0yPFDZgyo2LDtpVVAMhGNAfmQIj5uPva/pMtnzJXS/B5SFFqFTmPPZzZTwMsz1Ca7P3w36doBK+u6aYKKBMVFyoWKWSecX53hxGgkK+4xznYl2zhav0IwNeLQeX4T7koJB7c/gIFt+I8NmPguuMkWS8p2eJ4YZQfY/z6Cjhkj49x4hpa3/Nvn/Hz1PfrEFhubWV/Ll0egdrzY7cu4EAzHJzC8cS19PbM+CdUbfic0jJ8oIEeuQSMNMIYDEGn7jRNj3s1TAQt3WaIsgU6NmgJDo/KWFvMLTvipHxV3wIuO5OEfK67lVTQteqKScDwvS0fr97uEaV6/xt0PlvqgWKcEJk5992PuftHw3n7NBHFZ9bX5biFZ2lsnjhqmvPCx3KP+g9EOm9xTUswkrvW7fJyUraHKedqtDRlP5ouN70viPPvAw6iE1o3cytaANuQdl6xXRmU7RvyqBeOGhaxqTomVJaZu3YusU9LqRoa5k5J8yW08rwzpL5qR47AHStNFIZnQO8sJSJiSKzrIHJJqtP9JPjEWIDyHbMM7bj1G13I2S2gl1IAmKVuChl7Oas4cKp3L1o2FX026HEUgS6hn9GflCKSSz/6sXooj19mWT41IAcfETdmSvwteB/Wc7pdCf4SK83c0ZKiPSh5bj6bgKx+IhHsramQlsTaWvQaiFVjVFecjtlwQHyBiCHxnQZq1V71a1a4BPLti/qlz+siLbZDIsAmpyqApp7uwzUx3grqeawzuA/gCJyAgJnKQJ9cgu8hr6XBlt5skS8dQOoGs+l07/KVfouy4mHvcbucWgyWbOS26AiHnn5U3ExmtZPphIKHoZVE9t/IYKUTW+hsX1ZvUyWxndf5M6S0u8HFstOqFsF3ewEed3u5M6zbBuH3suWSTy5YJ/+QIlqHrYPYKH9XwmmkOyLj4EP6W+a97TuI5KX1Npd2ugFYxS0STNYEGPWvwPs0pZfRTE7CAAplbaKL7BEqbEIDTcNDNl5nOlyTuXNsDq0YoHfACMT8hyPk1HurtsR7nzoeOY8IIAmJU7WAhr7EwCdSilSOykG/n+WVfXt1/RAtetlADZCKyR8wEmbCW69ROQfpyOlaIEKvqZGE2RNeeoSqEBQ63RtsZ8nS0Y4+0A3rhx1zbMzArgQka53D1qrylwQh+FgwxrUegyDjZCtIE3HE67Ye61+QDuzfrGfAIgmeqgsJBuMZaKmXsE8OQ+pmlsg8KOYtngCoAw2d4g1EtXMq4HJHP10WviFkB7hPZegifXuLXx4Kx1mPVBDVXec/oQcbaF3V3H9jGQsoMwn+sDkHWhqmPuw7+Fhrz7CGKsPPGPao1ZZwLyWoiEBAje4ROD22H+0n+2INwxGwjXwbSXwsUtj1zCmwx4Ho3OMHa4UgrlorZnnmKzSB8mHfpdTcYLz2h96woRu0GedK4Wh00LPme6L1tzGsuo3zvhiZnn/4klLo0GVRhrn7pwtwgf98hZ/jxMflvuyJyJXqgjN4kTErjCnPHFwCh+DFKSrwhJ6Nq/jLKPybyL4jccsd2PL5ydL/uIOUDp84OZOgrBZDpEVvTUtb9Yyj6bkrOlfWHPrSisjDyVvPwCKQTAF7LTLeFgUaUnpCMDDHFOGV35yUQTT1EBhIa5eh8OV5Mf42WaC2fPsyCdgaxwAVDtIcobMgPcJ8FfgGt7KwCp4vUiMwj50qLLuvctVXDA4FZAIlwzFvX+ePrGQt4htk6Ei0QGtzo01VixQwCDpNStpqkJhBfNJOsH073rn8rJzF/XdsuveoS68kQ9Vu5td2Wr2pzGVOtYrZpTakDW+6DRud5FYIz4RWYJ9/WrJc5BYiw+8x65LQ3M6oW9P/3il5/5pXejsFPrwd7XgAd/Du88AqZUaMtElY/W8qm/INVjW1iU15qfLF44s+a8xgh/j7hMKqyTCpH4JsrSCSDXdzoE8wD9m6X4TgIbis9aygHxIKz64KGGfnQ+0LXgOsM5OmldH3xZiSRZHfmo3sH9smU6RelSYkpI+e4k5HLcFUpq69pISF+gpUtEQJmfOKEj5N2jCarPlfGM+MLOYSSB6FIRYyKiQZS1FJOSjnnYSvz2eP4SNmTFp6I+i84FlAOdamzF/eEe8r3J2ooq5ecxAoilgJgjb22hEZOlUfA7AsuICRnAs4Rc4vS8dmI9kPImalCFEhKvoEEvlkNP+Nlr1TBKVmUAGSHZPDEwSYkzl18YZpdvVD6uorKjJqU50llTLgBhyyk7HSrLFaRA8VFaIOjQzDGm1oaqkwkOtZjtrhlFmizJBAgAGsQZ5nV59rNn2hr+MziWIf5Vz0AEIh/hs9sByOXsVkCxRjuCkEPVJiziTxT7Gq1K+FRwI9gh7fjrtbisbeRUavXIafxI3p6wtA04tUmgytNIVvBR0dvdKAYP72F7m8tjmdAlfrGak/SOEejsdXQ9HRCpcLjZIUs9j0YfIAKqL2F7epR/F6Tsekka7IcRUr5jm42n7kLbxTo8p8WxVN9sBTMJzGMBjht0IGAu0wsUHeiqnmroKgP20d60BhjuW/yy6BZPK97aaYhL+Y/8CqZC8812dgFdxQSXK2JLrA61xmn4U8qRE0wV1vxmFEi5EmK8Nc+YA+1gTN6jARyOmClq8pOzI7WvJqVBHRhH7KynEUCjj1wouvEED8orVfAKFbCuFtxvIhqcWmKV5DG1i4Ig3n4VTu3cLShS4YZPq8pwvVuyumJnKiF5fYo0U8owEGb8/5TORvSsIuUOBi8VS8Cvdhk7T7f+9cS8U3gCOdwThKCIxGIhnT8o7sksJqxWOuh3hEFIH7VZ+5rYla4Dt57GUtwHBnZ2hjzfwPz/mUEmGjwY7FUDS+ljC+YM3q8DnXQ9HxlY45AcpU0fF+SieKxahjqFCE7SXJQszt7KrKgb8YLn8OcL2ZUQlk1MZhEqZRKwnm88CvfdyqytM5pu/p1NUb/uK9gCjPQ47kBk3j2EYwKlQmRgP7zlrKbPKGcf7VrjCRUDgoTjf0KNPV481XQRpeoTnBHipBy8mOY0ku1PtuwPAPWURujkfPRl+Zx45ffv0BMqz5bc2gN4pT6evHqw4o+3xvMt1zm/3g4P+KpnQf//4Q2s5KzAbbnd8IJNLh/4jnSgaXtUjaUy5cY31GXE70YAA7Sy6U6WBfSXSxjcYVhsSA1vAKD9TIkLGFrtZL5hyHKs4d4o5PDKjrc2PI6dBtrVy0tm/RiAinQQ5u3HJ2XjcWkf2RX2FZ+xXSichE54Zal5dIbdN1lSi3ZpNGVKLDrMcsPexW6irlubzO+8iIHRq4VFegujTltkMR+X25Z6ASwmxAdy28l36l1wCad5pbFrdplBVKJ+MdTMPyhcE9rzvEX5SNuZjycYA249HB7NnyfpWOAspWlbyLFoO3iF8JYFhNXAMttApT2yTpNVnUH7bR4VwBhEE2/FKAt3zGJBX81R5OnTXoZu9yEbMQ4pV7gpXUZlZutdXvHT8/7ExretvXAIIsmJP/XvATNFafo+C1fRAk9aJXU2l1+pgpDPnMmEE0f3YCtCL0jR07P7j5Rx7gmqskjoNQ04C0gxBWI6gqYF/lrkCr2tRHweVnTtBq6nntrpzT8+4HQmT7FvnOcHy+zH5cQwh54R0Rqmo7+dtSyQ++0Fb3kJupSqT38spmPAU3nRrdPtOdV0EIQEQzAPx823DDu366yi12qXbd2+ZpYRLIBbPVKSHhf92TOrrIN53vXkgIUIXDkzdOTDs77F82HQqSKw6evnaOf8eLt2UNay7qDkdNR4/leC3HtI29hmpK6es+NXVhqWf24ngq7YMmkM0O/QH5gUBcUAfRCRS0d/bgcOW46V74qJIncBekp8jY5K8//d47vV7D+aUcYN9Xv10nXGlbkzaGfQSTLUJyoYUUgn470rA6D5xpClqM/tzyW7EnwTIFVivLkkaqU+KNSEOzI/it+3CTL3D8Mmn7YEpMtJ1tiTT9MhazIxGbUDDLX51WvaBIV1/GYNOv2cdXuWKaJ0Dz+lKVDfg7wwYZBlRNRYXsX66lgNz/VfK+eKQaYo14sFxth1ov4rUkmzq52K9G1tSHCveKEqcM8aa5KQm7ahdo/thfzLvwyGgMhOqKefXtDwhQ/dI9omMnG1t9fn3gbTUA2OouV1xnRfUpNymBrreDmFRTayqO7f/f0yJGoT2p0wHvUdysvQQrL5jjnpsrYuP089861avBtiyugS7g4OcSiHU/mmxeYmZAW4wrS0+kMZmLHeSHuwPADeFPUszoveoYykV4oBWyhIfvTEK5Bt51Pw0/ddDBFJIqZI33pIDGJsd67xwU80Rzlp5zK6HMlLf1VSAj6sYscVsqUgPPwV3rsZ50C6faG3i25QFvKDDSBUANAuXW7nTI7QYgdQqlsQJc0H+9mmNqm1V6rHp6gBym0nQRExNU11vG8bd/kLRiO83GXsAJ+uiVF1cj7ODd9XdF81aj162VNNyMKamRKopAsdUio+i8kAaXn6SfzxYxlVdhv99cqxKD1voNTJ4Ov7U9s/ynOCM2OKvULQNDc9R6Q69m3rWX8hAd3fRGFm6I9G7LaShj7+tQsFK9pLVILVCT5VMrwKeR/QpLKsA0ATk0VBnkPlVEHbD2xBI5AXty9U/Pil7E/fb2tYHVR2ltJE78foetsFQ36dYkmkeGVUwb+958KhSAs333wHtIpWytnFSUxsF4+RXqqHTUiV7s0RSD96r8PGNFWXhFgPF5hvt8+oRtHzthdbECg9c0HuptwbbjuMn1Hw7pZf1FIJm8bAvrC0GxV3dCdqvpgMqhWtDew+iPj2vys+1qF81m1qYixe+U5CXrnCKlYGq6+rZ64uaB+uwwPMEe0SSpLd/u8UVVE1fKweV+PaVnlahPft01zoJ7xb2659xM9sFXFjPc7MUx4o6BGFYj2VxXZhxPgxiCH7Kk34wrSJV6L7Khg4K+aGW64FiFJW9ungQwC2LgIiqgBx42w00Ow1/09fFfNn8JOWvpDWOK1S06MPnvckTYRDpSLDt183OShR6gclZfOyG/ByzRy9sAw==
---
kind: signature
hmac: a11d47376e512f6bf69ef32457271f3f1a040d7fb186287cfd58db66666dc2b2

...
